# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5bdc8294b277c4a2e1318672094327756f6afb6e6ed3dc43c3698ddee789ba544cfaa21674ee1b6b2a6a0e338b59071129a2b84e345a77b43fae940dc8e1b805

test:
  secret_key_base: 4bc5a30c97d311d7ea4faf6e11fe3d9ed27b4cd9f575fd73315b198d3409bd56a67ed0ef17568f7cf0810d4732a79a5a2167fb738dd88a1f3570fc200075a37a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
